name: Assign New Issues

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Assign Issue to Team Member
        uses: actions-ecosystem/action-assign@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: 'Jasmine-hurt'
